name: CI/CD

on:
  push:
    branches: [ "master", "develop", "feature/**" ]
  pull_request:
    branches: [ "master", "develop", "feature/**" ]

env:
  PROJECT_NAME: samokatim-monitoring-service

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Docker Hub login
        run: docker login --username ${{ secrets.USERNAME_HUB }} --password ${{ secrets.PASSWORD_HUB }}
      - name: Docker build
        run: docker build --tag ${{ secrets.USERNAME_HUB }}/$PROJECT_NAME:$GITHUB_RUN_NUMBER .
      - name: Docker push
        run: docker push ${{ secrets.USERNAME_HUB }}/$PROJECT_NAME:$GITHUB_RUN_NUMBER
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Helm Deploy
        uses: vimeda/helm@v1.6.8
        with:
          namespace: 'samokatim-backend'
          release: 'monitoring-service'
          chart: 'helm'
          token: '${{ github.token }}'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'