name: CI/CD

on:
  push:
    branches: [ "master", "develop", "feature/**" ]
  pull_request:
    branches: [ "master", "develop", "feature/**" ]

env:
  PROJECT_NAME: samokatim-monitoring-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Docker Hub login
        run: docker login --username ${{ secrets.USERNAME_HUB }} --password ${{ secrets.PASSWORD_HUB }}
      - name: Docker build
        run: docker build --tag ${{ secrets.USERNAME_HUB }}/$PROJECT_NAME:latest .
      - name: Docker push
        run: docker push ${{ secrets.USERNAME_HUB }}/$PROJECT_NAME:latest
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: 'deliverybot/helm@v1'
        with:
          release: $PROJECT_NAME
          namespace: default
          chart: helm
          token: ${{ github.token }}
          values: |
            name: helm
          value-files: [
            "values.yaml"
          ]
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}